// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const ArrowPathRoundedSquare = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path fillRule="evenodd" d="M8 3.5q-1.157 0-2.297.066a1.124 1.124 0 0 0-1.058 1.028l-.018.214a.75.75 0 1 1-1.495-.12l.018-.221a2.624 2.624 0 0 1 2.467-2.399 42 42 0 0 1 4.766 0 2.624 2.624 0 0 1 2.467 2.399q.084.993.122 2l.748-.748a.75.75 0 1 1 1.06 1.06l-2 2.001a.75.75 0 0 1-1.061 0l-2-1.999a.75.75 0 0 1 1.061-1.06l.689.688a40 40 0 0 0-.114-1.815 1.124 1.124 0 0 0-1.058-1.028A40 40 0 0 0 8 3.5M3.22 7.22a.75.75 0 0 1 1.061 0l2 2a.75.75 0 1 1-1.06 1.06l-.69-.69q.037.914.114 1.816c.048.56.496.996 1.058 1.028a40 40 0 0 0 4.594 0 1.124 1.124 0 0 0 1.058-1.028l.018-.219a.75.75 0 1 1 1.495.12l-.018.226a2.624 2.624 0 0 1-2.467 2.399 42 42 0 0 1-4.766 0 2.624 2.624 0 0 1-2.467-2.399 41 41 0 0 1-.122-2l-.748.748A.75.75 0 1 1 1.22 9.22z" clipRule="evenodd" />
    </Svg>
  );
};

export default ArrowPathRoundedSquare;
