// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const Calculator = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path fillRule="evenodd" d="M5 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2zm.75 6a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5M5 3.75A.75.75 0 0 1 5.75 3h4.5a.75.75 0 0 1 0 1.5h-4.5A.75.75 0 0 1 5 3.75m.75 7.75a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5M5 10a.75.75 0 1 1 1.5 0A.75.75 0 0 1 5 10m5.25-3a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5m-.75 3a.75.75 0 0 1 1.5 0v2.25a.75.75 0 0 1-1.5 0zM8 7a.75.75 0 1 0 0 1.5A.75.75 0 0 0 8 7m-.75 5.25a.75.75 0 1 1 1.5 0 .75.75 0 0 1-1.5 0m.75-3a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5" clipRule="evenodd" />
    </Svg>
  );
};

export default Calculator;
