// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const CalendarDays = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M5.75 7.5a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5M5 10.25a.75.75 0 1 1 1.5 0 .75.75 0 0 1-1.5 0m5.25-2.75a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5m-3 .75a.75.75 0 1 1 1.5 0 .75.75 0 0 1-1.5 0M8 9.5A.75.75 0 1 0 8 11a.75.75 0 0 0 0-1.5" /><Path fillRule="evenodd" d="M4.75 1a.75.75 0 0 0-.75.75V3a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2V1.75a.75.75 0 0 0-1.5 0V3h-5V1.75A.75.75 0 0 0 4.75 1M3.5 7a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v4.5a1 1 0 0 1-1 1h-7a1 1 0 0 1-1-1z" clipRule="evenodd" />
    </Svg>
  );
};

export default CalendarDays;
