// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const FingerPrint = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path fillRule="evenodd" d="M8 3c-.988 0-1.908.286-2.682.78a.75.75 0 0 1-.806-1.266A6.5 6.5 0 0 1 14.5 8c0 1.665-.333 3.254-.936 4.704a.75.75 0 0 1-1.385-.577C12.708 10.857 13 9.464 13 8a5 5 0 0 0-5-5M3.55 4.282a.75.75 0 0 1 .23 1.036A4.97 4.97 0 0 0 3 8a.75.75 0 0 1-1.5 0c0-1.282.372-2.48 1.014-3.488a.75.75 0 0 1 1.036-.23M8 5.875A2.125 2.125 0 0 0 5.875 8a3.625 3.625 0 0 1-3.625 3.625h-.037a.75.75 0 1 1 .008-1.5h.03A2.125 2.125 0 0 0 4.376 8a3.625 3.625 0 1 1 7.25 0q0 .117-.003.233a.75.75 0 1 1-1.5-.036L10.126 8A2.125 2.125 0 0 0 8 5.875M7.995 7.25a.75.75 0 0 1 .75.75 6.5 6.5 0 0 1-4.343 6.133.75.75 0 1 1-.498-1.415A5 5 0 0 0 7.245 8a.75.75 0 0 1 .75-.75m2.651 2.87a.75.75 0 0 1 .463.955 9.4 9.4 0 0 1-3.008 4.25.75.75 0 0 1-.936-1.171 7.9 7.9 0 0 0 2.527-3.57.75.75 0 0 1 .954-.463Z" clipRule="evenodd" />
    </Svg>
  );
};

export default FingerPrint;
