// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const Flag = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M2.75 2a.75.75 0 0 0-.75.75v10.5a.75.75 0 0 0 1.5 0v-2.624l.33-.083A6.04 6.04 0 0 1 8 11c1.29.645 2.77.807 4.17.457l1.48-.37a.46.46 0 0 0 .35-.448V3.56a.438.438 0 0 0-.544-.425l-1.287.322A6.04 6.04 0 0 1 8 3a6.05 6.05 0 0 0-4.17-.457l-.34.085A.75.75 0 0 0 2.75 2" />
    </Svg>
  );
};

export default Flag;
