// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const Power = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path fillRule="evenodd" d="M8 1a.75.75 0 0 1 .75.75v6.5a.75.75 0 0 1-1.5 0v-6.5A.75.75 0 0 1 8 1M4.11 3.05a.75.75 0 0 1 0 1.06 5.5 5.5 0 1 0 7.78 0 .75.75 0 0 1 1.06-1.06 7 7 0 1 1-9.9 0 .75.75 0 0 1 1.06 0" clipRule="evenodd" />
    </Svg>
  );
};

export default Power;
