// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const QrCode = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M4.75 4.25a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1" /><Path fillRule="evenodd" d="M2 3.5A1.5 1.5 0 0 1 3.5 2H6a1.5 1.5 0 0 1 1.5 1.5V6A1.5 1.5 0 0 1 6 7.5H3.5A1.5 1.5 0 0 1 2 6zm1.5 0H6V6H3.5z" clipRule="evenodd" /><Path d="M4.25 11.25a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0" /><Path fillRule="evenodd" d="M2 10a1.5 1.5 0 0 1 1.5-1.5H6A1.5 1.5 0 0 1 7.5 10v2.5A1.5 1.5 0 0 1 6 14H3.5A1.5 1.5 0 0 1 2 12.5zm1.5 2.5V10H6v2.5z" clipRule="evenodd" /><Path d="M11.25 4.25a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1" /><Path fillRule="evenodd" d="M10 2a1.5 1.5 0 0 0-1.5 1.5V6A1.5 1.5 0 0 0 10 7.5h2.5A1.5 1.5 0 0 0 14 6V3.5A1.5 1.5 0 0 0 12.5 2zm2.5 1.5H10V6h2.5z" clipRule="evenodd" /><Path d="M8.5 9.417a.917.917 0 1 1 1.833 0 .917.917 0 0 1-1.833 0m0 3.666a.917.917 0 1 1 1.833 0 .917.917 0 0 1-1.833 0M13.083 8.5a.917.917 0 1 0 0 1.833.917.917 0 0 0 0-1.833m-.917 4.584a.917.917 0 1 1 1.833 0 .917.917 0 0 1-1.833 0m-.916-2.751a.917.917 0 1 0 0 1.833.917.917 0 0 0 0-1.833" />
    </Svg>
  );
};

export default QrCode;
