// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const Scale = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path fillRule="evenodd" d="M8.75 2.5a.75.75 0 0 0-1.5 0v.508a33 33 0 0 0-4.624.434.75.75 0 0 0 .246 1.48l.13-.021-1.188 4.75a.75.75 0 0 0 .33.817A3.5 3.5 0 0 0 4 11a3.5 3.5 0 0 0 1.856-.532.75.75 0 0 0 .33-.818l-1.25-5a31 31 0 0 1 2.314-.141v7.503q-1.324.042-2.607.226a.75.75 0 0 0 .213 1.485 22.2 22.2 0 0 1 6.288 0 .75.75 0 1 0 .213-1.485 24 24 0 0 0-2.607-.226V4.509q1.168.028 2.314.14L9.814 9.65a.75.75 0 0 0 .329.818 3.5 3.5 0 0 0 1.856.532 3.5 3.5 0 0 0 1.856-.532.75.75 0 0 0 .33-.818L12.997 4.9l.13.022a.75.75 0 1 0 .247-1.48 33 33 0 0 0-4.624-.434zM3.42 9.415a2 2 0 0 0 1.16 0L4 7.092zM12 9.5a2 2 0 0 1-.582-.085L12 7.092l.58 2.323A2 2 0 0 1 12 9.5" clipRule="evenodd" />
    </Svg>
  );
};

export default Scale;
