// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const ServerStack = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M5.354 2a2 2 0 0 0-1.857 1.257l-.338.845A3.5 3.5 0 0 1 4 4h8q.436 0 .84.102l-.337-.845A2 2 0 0 0 10.646 2z" /><Path fillRule="evenodd" d="M2 13a2 2 0 0 1 2-2h8a2 2 0 1 1 0 4H4a2 2 0 0 1-2-2m10.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0M9 13.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5M4 5.5a2 2 0 1 0 0 4h8a2 2 0 1 0 0-4zm8 2.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5M9.75 7.5a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0" clipRule="evenodd" />
    </Svg>
  );
};

export default ServerStack;
