// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const ShieldExclamation = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path fillRule="evenodd" d="M7.5 1.709a.75.75 0 0 1 1 0 8.96 8.96 0 0 0 4.84 2.217.75.75 0 0 1 .654.72 10.5 10.5 0 0 1-5.647 9.672.75.75 0 0 1-.694-.001 10.5 10.5 0 0 1-5.647-9.672.75.75 0 0 1 .654-.719A8.96 8.96 0 0 0 7.5 1.71ZM8 5a.75.75 0 0 1 .75.75v2a.75.75 0 0 1-1.5 0v-2A.75.75 0 0 1 8 5m0 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2" clipRule="evenodd" />
    </Svg>
  );
};

export default ShieldExclamation;
