// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const SignalSlash = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M3.28 2.22a.75.75 0 0 0-1.06 1.06l4.782 4.783a1 1 0 0 0 .935.935l4.783 4.782a.75.75 0 1 0 1.06-1.06L8.998 7.937a1 1 0 0 0-.935-.935zm-.23 10.73a7 7 0 0 1-1.33-8.047L2.86 6.04a5.5 5.5 0 0 0 1.25 5.849.75.75 0 1 1-1.06 1.06Zm2.21-2.21a3.87 3.87 0 0 1-1.082-3.38L5.87 9.052c.112.226.262.439.45.627a.75.75 0 1 1-1.06 1.061m7.69-7.69a7 7 0 0 1 1.33 8.048l-1.14-1.139a5.5 5.5 0 0 0-1.25-5.848.75.75 0 0 1 1.06-1.06Zm-2.21 2.21a3.87 3.87 0 0 1 1.082 3.38L10.13 6.948a2.4 2.4 0 0 0-.45-.627.75.75 0 0 1 1.06-1.061" />
    </Svg>
  );
};

export default SignalSlash;
