// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const Truck = ({
  size = 16,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M2.908 2.067A.98.98 0 0 0 2 3.05V8h6V3.05a.98.98 0 0 0-.908-.983 32.5 32.5 0 0 0-4.184 0m10.011 2.655A.98.98 0 0 0 11.968 4H10a1 1 0 0 0-1 1v6.268A2 2 0 0 1 12 13h1a.977.977 0 0 0 .985-1 32 32 0 0 0-1.066-7.278" /><Path d="M11 13a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-9-1V9h6v3a1 1 0 0 1-1 1 2 2 0 1 0-4 0 1 1 0 0 1-1-1" /><Path d="M6 13a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
    </Svg>
  );
};

export default Truck;
