// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const PlayPause = ({
  size = 24,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M15 6.75a.75.75 0 0 0-.75.75V18a.75.75 0 0 0 .75.75h.75a.75.75 0 0 0 .75-.75V7.5a.75.75 0 0 0-.75-.75zm5.25 0a.75.75 0 0 0-.75.75V18c0 .414.336.75.75.75H21a.75.75 0 0 0 .75-.75V7.5a.75.75 0 0 0-.75-.75zm-15.195.31c-1.25-.713-2.805.19-2.805 1.63v8.122c0 1.44 1.555 2.343 2.805 1.628l7.108-4.061c1.26-.72 1.26-2.536 0-3.256L5.055 7.061Z" />
    </Svg>
  );
};

export default PlayPause;
