// 🌊 Refactored carefully for Bun. Zero logic regressions.
import path from 'path';
import fs from 'fs';
import { transform } from '@svgr/core';

const ICON_SIZES = [16, 20, 24];
const ICON_STYLES = ['solid', 'outline'];

const HEROICONS_DIR = path.join(import.meta.dir, 'hero/optimized');
const OUTPUT_DIR = path.join(import.meta.dir, '..');

async function generateIconComponent(svgContent: string, size: number, style: string, filename: string): Promise<string> {
  const isOutline = style === 'outline';
  const componentName = getComponentName(filename);

  // Pre-process SVG: add fill="currentColor" to path elements that don't have fill
  let processedSvg = svgContent.replace(/<path([^>]*?)\/>/g, (match, attrs) => {
    if (!attrs.includes('fill=')) {
      return '<path' + attrs + ' fill="currentColor"/>';
    }
    return match;
  });

  const transformed = await transform(
    processedSvg,
    {
      native: true,
      expandProps: 'end',
      replaceAttrValues: {
        '#111827': '{finalColor}',
        '#212121': '{finalColor}',
        'currentColor': '{finalColor}',
      },
      plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
      svgProps: {
        width: '{size}',
        height: '{size}',
        viewBox: '0 0 24 24',
        fill: isOutline ? 'none' : '{finalColor}',
        stroke: isOutline ? '{finalColor}' : 'none',
      },
    },
    { caller: { name: '@svgr/core' } }
  );

  // Extract the inner content (Path elements) from the transformed JSX
  const svgContentMatch = transformed.match(/<Svg[^>]*>([\s\S]*)<\/Svg>/);
  const innerContent = svgContentMatch ? svgContentMatch[1].trim() : '';

  // Create the component template manually
  const componentTemplate = `// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const ${componentName} = ({
  size = ${size},
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = ${isOutline};
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
${innerContent.split('\n').map(line => '      ' + line).join('\n')}
    </Svg>
  );
};

export default ${componentName};
`;

  return componentTemplate;
}

function getComponentName(filename: string): string {
  return path.basename(filename, '.svg')
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

async function generateIcons() {
  for (const size of ICON_SIZES) {
    for (const style of ICON_STYLES) {
      const inputDir = path.join(HEROICONS_DIR, String(size), style);
      const outputDir = path.join(OUTPUT_DIR, String(size), style);

      if (!fs.existsSync(inputDir)) {
        continue;
      }

      fs.mkdirSync(outputDir, { recursive: true });

      const files = fs.readdirSync(inputDir).filter(f => path.extname(f) === '.svg');

      for (const file of files) {
        const svgPath = path.join(inputDir, file);
        const svgContent = fs.readFileSync(svgPath, 'utf-8');
        const componentName = getComponentName(file);
        const outputPath = path.join(outputDir, `${componentName}.tsx`);

        const componentCode = await generateIconComponent(svgContent, size, style, file);
        fs.writeFileSync(outputPath, componentCode);
        console.log(`Generated: ${outputPath}`);
      }
    }
  }
}

function generateIndexFile(size: number, style: string) {
  const dir = path.join(OUTPUT_DIR, String(size), style);
  if (!fs.existsSync(dir)) return;

  const files = fs.readdirSync(dir).filter(f => f.endsWith('.tsx'));
  const exports = files
    .map(f => {
      const name = f.split('.')[0]; // Maintained original implementation fix
      return `export { default as ${name} } from './${name}';`;
    })
    .join('\n');

  const indexPath = path.join(dir, 'index.ts');
  fs.writeFileSync(indexPath, exports + '\n');
  console.log(`Generated index: ${indexPath}`);
}

function generateMainIndexFiles() {
  for (const size of ICON_SIZES) {
    for (const style of ICON_STYLES) {
      generateIndexFile(size, style);
    }
  }

  // Generate main index files for each size
  for (const size of ICON_SIZES) {
    const sizeDir = path.join(OUTPUT_DIR, String(size));
    const styles = ICON_STYLES.filter(s => fs.existsSync(path.join(sizeDir, s)));

    const exports = styles
      .map(style => `export * from './${style}';`)
      .join('\n');

    fs.writeFileSync(path.join(sizeDir, 'index.ts'), exports + '\n');
    console.log(`Generated main index: ${path.join(sizeDir, 'index.ts')}`);
  }

  // Generate root index
  const rootExports = ICON_SIZES.map(size => `export * from './${size}';`).join('\n');
  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), rootExports + '\n');
  console.log('Generated root index.ts');
}

async function main() {
  await generateIcons();
  generateMainIndexFiles();
  console.log('✅ Generation complete!');
}

main().catch(console.error);