// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const BookOpen = ({
  size = 20,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M10.75 16.82A7.46 7.46 0 0 1 15 15.5a7.5 7.5 0 0 1 2.046.282.75.75 0 0 0 .954-.722v-11a.75.75 0 0 0-.546-.721A9 9 0 0 0 15 3a8.96 8.96 0 0 0-4.25 1.065zM9.25 4.065A8.96 8.96 0 0 0 5 3a9 9 0 0 0-2.454.339A.75.75 0 0 0 2 4.06v11a.75.75 0 0 0 .954.721A7.5 7.5 0 0 1 5 15.5c1.579 0 3.042.487 4.25 1.32z" />
    </Svg>
  );
};

export default BookOpen;
