// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const CurrencyDollar = ({
  size = 20,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M10.75 10.818v2.614A3.1 3.1 0 0 0 11.888 13c.482-.315.612-.648.612-.875s-.13-.56-.612-.875a3.1 3.1 0 0 0-1.138-.432M8.33 8.62q.08.083.184.164c.208.16.46.284.736.363V6.603a2.5 2.5 0 0 0-.35.13 2 2 0 0 0-.386.233c-.377.292-.514.627-.514.909 0 .184.058.39.202.592q.056.077.128.152Z" /><Path fillRule="evenodd" d="M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0m-8-6a.75.75 0 0 1 .75.75v.316a3.8 3.8 0 0 1 1.653.713c.426.33.744.74.925 1.2a.75.75 0 0 1-1.395.55 1.35 1.35 0 0 0-.447-.563 2.2 2.2 0 0 0-.736-.363V9.3c.698.093 1.383.32 1.959.696.787.514 1.29 1.27 1.29 2.13s-.504 1.616-1.29 2.13c-.576.377-1.261.603-1.96.696v.299a.75.75 0 1 1-1.5 0v-.3c-.697-.092-1.382-.318-1.958-.695-.482-.315-.857-.717-1.078-1.188a.75.75 0 1 1 1.359-.636c.08.173.245.376.54.569.313.205.706.353 1.138.432v-2.748a3.8 3.8 0 0 1-1.653-.713C6.9 9.433 6.5 8.681 6.5 7.875c0-.805.4-1.558 1.097-2.096a3.8 3.8 0 0 1 1.653-.713V4.75A.75.75 0 0 1 10 4" clipRule="evenodd" />
    </Svg>
  );
};

export default CurrencyDollar;
