// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const GlobeAlt = ({
  size = 20,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M16.555 5.412a8.03 8.03 0 0 0-3.503-2.81 14.9 14.9 0 0 1 1.663 4.472 8.6 8.6 0 0 0 1.84-1.662m-3.229 2.413a13.4 13.4 0 0 0-2.413-5.773 8 8 0 0 0-1.826 0 13.4 13.4 0 0 0-2.413 5.773A8.5 8.5 0 0 0 10 8.5c1.18 0 2.304-.24 3.326-.675M6.514 9.376A10 10 0 0 0 10 10c1.226 0 2.4-.22 3.486-.624a13.5 13.5 0 0 1-.351 3.759A13.5 13.5 0 0 1 10 13.5c-1.079 0-2.128-.127-3.134-.366a13.5 13.5 0 0 1-.352-3.758M5.285 7.074a14.9 14.9 0 0 1 1.663-4.471 8.03 8.03 0 0 0-3.503 2.81 8.6 8.6 0 0 0 1.84 1.66Zm12.049-.276a8 8 0 0 1 .614 4.115 13.5 13.5 0 0 1-3.178 1.72 15 15 0 0 0 .174-3.939 10 10 0 0 0 2.39-1.896m-14.668 0a10 10 0 0 0 2.39 1.896 15.2 15.2 0 0 0 .174 3.94 13.5 13.5 0 0 1-3.178-1.72 8 8 0 0 1 .615-4.115ZM10 15q1.349-.002 2.633-.23a13.5 13.5 0 0 1-1.72 3.178 8 8 0 0 1-1.826 0 13.5 13.5 0 0 1-1.72-3.178q1.284.228 2.633.23m4.357-.643a15 15 0 0 1-1.305 3.04 8.03 8.03 0 0 0 4.345-4.345c-.953.542-1.971.981-3.04 1.305m-7.409 3.04a8.03 8.03 0 0 1-4.345-4.345c.953.542 1.971.981 3.04 1.305a15 15 0 0 0 1.305 3.04" />
    </Svg>
  );
};

export default GlobeAlt;
