// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const Lifebuoy = ({
  size = 20,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path fillRule="evenodd" d="m7.171 4.146 1.947 2.466a3.5 3.5 0 0 1 1.764 0l1.947-2.466a6.52 6.52 0 0 0-5.658 0m8.683 3.025-2.466 1.947c.15.578.15 1.186 0 1.764l2.466 1.947a6.52 6.52 0 0 0 0-5.658m-3.025 8.683-1.947-2.466c-.578.15-1.186.15-1.764 0l-1.947 2.466a6.52 6.52 0 0 0 5.658 0M4.146 12.83l2.466-1.947a3.5 3.5 0 0 1 0-1.764L4.146 7.171a6.52 6.52 0 0 0 0 5.658ZM5.63 3.297a8.01 8.01 0 0 1 8.738 0 8 8 0 0 1 2.334 2.334 8.01 8.01 0 0 1 0 8.738 8 8 0 0 1-2.334 2.334 8.01 8.01 0 0 1-8.738 0 8 8 0 0 1-2.334-2.334 8.01 8.01 0 0 1 0-8.738A8 8 0 0 1 5.63 3.297m5.198 4.882a2.01 2.01 0 0 0-2.243.407 1.99 1.99 0 0 0-.407 2.243 2 2 0 0 0 .992.992 2.01 2.01 0 0 0 2.243-.407c.176-.175.31-.374.407-.585a2.01 2.01 0 0 0-.407-2.243 2 2 0 0 0-.585-.407" clipRule="evenodd" />
    </Svg>
  );
};

export default Lifebuoy;
