// 🌊 this file is auto-generated by generate script. don't edit it.
// https://github.com/nandorojo/react-native-desktop-heroicons
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

interface IconProps extends SvgProps {
  size?: number;
  fill?: string;
  stroke?: string;
  color?: string;
}

const QueueList = ({
  size = 20,
  fill,
  stroke,
  color,
  ...props
}: IconProps) => {
  const isOutline = false;
  const finalColor = isOutline
    ? (stroke || color || '#111827')
    : (fill || color || '#111827');

  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={isOutline ? "none" : finalColor}
      stroke={isOutline ? finalColor : "none"}
      {...props}
    >
      <Path d="M2 4.5A2.5 2.5 0 0 1 4.5 2h11a2.5 2.5 0 0 1 0 5h-11A2.5 2.5 0 0 1 2 4.5m.75 4.583a.75.75 0 0 0 0 1.5h14.5a.75.75 0 0 0 0-1.5zm0 3.58a.75.75 0 0 0 0 1.5h14.5a.75.75 0 0 0 0-1.5zm0 3.587a.75.75 0 0 0 0 1.5h14.5a.75.75 0 1 0 0-1.5z" />
    </Svg>
  );
};

export default QueueList;
